QUIZ_RESULTS = {
    "SHRB": {
        "sakes": [
            {
                "name": "鳳凰美田 純米大吟醸",
                "brewery": "小林酒造",
                "region": "栃木県",
                "description": "華やかなマスカットの香りとクリアな酸味。",
                "imagePath": "/images/sake-placeholder.jpg",
                "tags": [
                    {"label": "Aromatic", "variant": "primary"},
                    {"label": "Chilled", "variant": "secondary"},
                ],
            },
            {
                "name": "醸し人九平次 希望の水",
                "brewery": "萬乗醸造",
                "region": "愛知県",
                "description": "ワインのような立体感とエレガントな余韻。",
                "imagePath": "/images/sake-placeholder.jpg",
                "tags": [
                    {"label": "Refined", "variant": "primary"},
                    {"label": "Room Temp", "variant": "secondary"},
                ],
            },
            {
                "name": "たかちよ 扁平精米",
                "brewery": "髙千代酒造",
                "region": "新潟県",
                "description": "完熟した果実味とジューシーな旨味の調和。",
                "imagePath": "/images/sake-placeholder.jpg",
                "tags": [
                    {"label": "Floral", "variant": "primary"},
                    {"label": "Summer", "variant": "secondary"},
                ],
            },
        ],
        "pairingSectionTitle": "美食の相性図鑑",
        "pairingSectionDescription": "SHRBタイプは、香りの重なりを愉しむマリアージュが得意。素材の甘みを引き立てる、繊細なペアリングをご提案します。",
        "pairings": [
            {
                "emoji": "🍣",
                "foodName": "白身魚の昆布締め",
                "sakeName": "フルーティーな大吟醸",
                "temperature": "冷酒 5-10°C",
                "description": "昆布の旨味を日本酒の華やかな香りが包み込み、鼻に抜ける余韻が完成されます。",
            },
            {
                "emoji": "🍓",
                "foodName": "フレッシュベリーの白和え",
                "sakeName": "微発泡濁り酒",
                "temperature": "冷酒 8-12°C",
                "description": "果実の酸とシュワっとした炭酸が、豆乳のまろやかさをリフレッシュさせます。",
            },
            {
                "emoji": "🫕",
                "foodName": "ブッラータチーズと季節の果実",
                "sakeName": "酸の高い原酒",
                "temperature": "常温",
                "description": "濃厚なクリーム感を、日本酒の持つ輪郭のある酸がスマートに引き締めます。",
            },
        ],
    },
    "SHRS": {
        "sakes": [
            {
                "name": "獺祭 純米大吟醸45",
                "brewery": "旭酒造",
                "region": "山口県",
                "description": "メロンのような甘い香りと、透明感のある滑らかな口当たり。",
                "imagePath": "/images/sake-placeholder.jpg",
                "tags": [
                    {"label": "Fruity", "variant": "primary"},
                    {"label": "Chilled", "variant": "secondary"},
                ],
            },
            {
                "name": "而今 純米吟醸",
                "brewery": "木屋正酒造",
                "region": "三重県",
                "description": "透き通るような甘みと、上品な余韻が心地よい。",
                "imagePath": "/images/sake-placeholder.jpg",
                "tags": [
                    {"label": "Elegant", "variant": "primary"},
                    {"label": "Year-round", "variant": "secondary"},
                ],
            },
            {
                "name": "花陽浴 純米大吟醸",
                "brewery": "南陽醸造",
                "region": "埼玉県",
                "description": "パイナップルのような華やかな香りと、柔らかな甘み。",
                "imagePath": "/images/sake-placeholder.jpg",
                "tags": [
                    {"label": "Sweet", "variant": "primary"},
                    {"label": "Chilled", "variant": "secondary"},
                ],
            },
        ],
        "pairingSectionTitle": "繊細な味わいの調和",
        "pairingSectionDescription": "SHRSタイプは、素材の繊細さを丁寧に拾い上げるペアリングが得意。静かに寄り添う組み合わせをどうぞ。",
        "pairings": [
            {
                "emoji": "🐟",
                "foodName": "鯛の薄造り",
                "sakeName": "華やかな純米大吟醸",
                "temperature": "冷酒 8°C",
                "description": "鯛の繊細な甘みに、大吟醸の優しい香りがそっと寄り添います。",
            },
            {
                "emoji": "🧀",
                "foodName": "リコッタチーズと蜂蜜",
                "sakeName": "甘口の純米",
                "temperature": "冷酒 10°C",
                "description": "クリーミーな食感と蜂蜜の甘さを、酒の上品な酸が引き立てます。",
            },
            {
                "emoji": "🥗",
                "foodName": "旬の野菜のおひたし",
                "sakeName": "軽快な吟醸",
                "temperature": "常温",
                "description": "出汁の旨味と野菜の優しい風味に、吟醸の穏やかな香りが調和します。",
            },
        ],
    },
    "SHLB": {
        "sakes": [
            {
                "name": "鍋島 New Moon",
                "brewery": "富久千代酒造",
                "region": "佐賀県",
                "description": "ジューシーな果実味と微かな発泡感が爽やか。",
                "imagePath": "/images/sake-placeholder.jpg",
                "tags": [
                    {"label": "Juicy", "variant": "primary"},
                    {"label": "Chilled", "variant": "secondary"},
                ],
            },
            {
                "name": "仙禽 オーガニック・ナチュール",
                "brewery": "せんきん",
                "region": "栃木県",
                "description": "自然な酸味とフレッシュな果実感が楽しい。",
                "imagePath": "/images/sake-placeholder.jpg",
                "tags": [
                    {"label": "Natural", "variant": "primary"},
                    {"label": "Summer", "variant": "secondary"},
                ],
            },
            {
                "name": "ソガ・ペール・エ・フィス",
                "brewery": "小布施ワイナリー",
                "region": "長野県",
                "description": "ワインのようなアプローチで醸す、個性的な日本酒。",
                "imagePath": "/images/sake-placeholder.jpg",
                "tags": [
                    {"label": "Unique", "variant": "primary"},
                    {"label": "Chilled", "variant": "secondary"},
                ],
            },
        ],
        "pairingSectionTitle": "軽やかな美の組み合わせ",
        "pairingSectionDescription": "SHLBタイプは、軽やかでありながら存在感のある食材との相性が抜群。爽やかな驚きを楽しんでください。",
        "pairings": [
            {
                "emoji": "🥗",
                "foodName": "生春巻き",
                "sakeName": "微発泡の純米吟醸",
                "temperature": "冷酒 5°C",
                "description": "フレッシュな野菜と海老の甘みに、発泡感が心地よいアクセント。",
            },
            {
                "emoji": "🧀",
                "foodName": "モッツァレラとトマト",
                "sakeName": "酸のある純米",
                "temperature": "冷酒 8°C",
                "description": "カプレーゼの酸味とチーズのミルキーさに、酒の爽やかさが映えます。",
            },
            {
                "emoji": "🍓",
                "foodName": "フルーツサラダ",
                "sakeName": "甘酸っぱい低アルコール酒",
                "temperature": "冷酒 5°C",
                "description": "果実味同士が華やかに重なり、デザート感覚で楽しめます。",
            },
        ],
    },
    "SHLS": {
        "sakes": [
            {
                "name": "澤屋まつもと 守破離",
                "brewery": "松本酒造",
                "region": "京都府",
                "description": "透明感あふれる味わいと、穏やかな余韻。",
                "imagePath": "/images/sake-placeholder.jpg",
                "tags": [
                    {"label": "Clear", "variant": "primary"},
                    {"label": "Year-round", "variant": "secondary"},
                ],
            },
            {
                "name": "雪の茅舎 純米吟醸",
                "brewery": "齋彌酒造店",
                "region": "秋田県",
                "description": "雪国の清らかさそのもの。柔らかく消えていく後味。",
                "imagePath": "/images/sake-placeholder.jpg",
                "tags": [
                    {"label": "Soft", "variant": "primary"},
                    {"label": "Chilled", "variant": "secondary"},
                ],
            },
            {
                "name": "上善如水 純米吟醸",
                "brewery": "白瀧酒造",
                "region": "新潟県",
                "description": "水のように滑らかで、どんな料理にもそっと寄り添う。",
                "imagePath": "/images/sake-placeholder.jpg",
                "tags": [
                    {"label": "Gentle", "variant": "primary"},
                    {"label": "Year-round", "variant": "secondary"},
                ],
            },
        ],
        "pairingSectionTitle": "静けさの中の美味",
        "pairingSectionDescription": "SHLSタイプは、穏やかで控えめな味わいの中に美を見出します。静かに味わう至福の時間をお届けします。",
        "pairings": [
            {
                "emoji": "🍲",
                "foodName": "湯豆腐",
                "sakeName": "穏やかな純米吟醸",
                "temperature": "常温",
                "description": "素材の繊細な旨味を、柔らかな酒がそっと引き立てます。",
            },
            {
                "emoji": "🐟",
                "foodName": "白身魚の蒸し物",
                "sakeName": "軽やかな純米",
                "temperature": "冷酒 10°C",
                "description": "蒸した魚の優しい味わいに、酒の透明感が静かに調和します。",
            },
            {
                "emoji": "🥬",
                "foodName": "胡麻豆腐",
                "sakeName": "滑らかな吟醸",
                "temperature": "冷酒 8°C",
                "description": "胡麻の濃厚な風味を、酒の軽やかさが上品にまとめます。",
            },
        ],
    },
    "SERB": {
        "sakes": [
            {
                "name": "新政 No.6 S-type",
                "brewery": "新政酒造",
                "region": "秋田県",
                "description": "シャープな酸味と白ぶどうのような華やかな香り。",
                "imagePath": "/images/sake-placeholder.jpg",
                "tags": [
                    {"label": "Modern", "variant": "primary"},
                    {"label": "Chilled", "variant": "secondary"},
                ],
            },
            {
                "name": "風の森 ALPHA TYPE1",
                "brewery": "油長酒造",
                "region": "奈良県",
                "description": "微発泡のフレッシュ感と、爽快な飲み心地。",
                "imagePath": "/images/sake-placeholder.jpg",
                "tags": [
                    {"label": "Fresh", "variant": "primary"},
                    {"label": "Summer", "variant": "secondary"},
                ],
            },
            {
                "name": "天美 純米吟醸",
                "brewery": "長州酒造",
                "region": "山口県",
                "description": "爽やかな柑橘感と、キレのある後味。",
                "imagePath": "/images/sake-placeholder.jpg",
                "tags": [
                    {"label": "Citrus", "variant": "primary"},
                    {"label": "Chilled", "variant": "secondary"},
                ],
            },
        ],
        "pairingSectionTitle": "爽快な冒険のテーブル",
        "pairingSectionDescription": "SERBタイプは、爽快さの中に力強さを持つペアリングが得意。意外な組み合わせにも果敢に挑戦してみてください。",
        "pairings": [
            {
                "emoji": "🦪",
                "foodName": "牡蠣のポン酢",
                "sakeName": "酸の効いた純米",
                "temperature": "冷酒 8°C",
                "description": "牡蠣のミネラルと酒の酸味が共鳴し、レモンのような爽快感。",
            },
            {
                "emoji": "🥩",
                "foodName": "ローストビーフ",
                "sakeName": "フルボディの原酒",
                "temperature": "常温",
                "description": "肉の旨味を酒のコクが受け止め、力強い味わいのマリアージュ。",
            },
            {
                "emoji": "🧀",
                "foodName": "ゴルゴンゾーラと蜂蜜",
                "sakeName": "甘口のにごり酒",
                "temperature": "冷酒 10°C",
                "description": "青カビの刺激を蜂蜜と酒の甘みが包み、大人のデザートに。",
            },
        ],
    },
    "SERS": {
        "sakes": [
            {
                "name": "写楽 純米吟醸",
                "brewery": "宮泉銘醸",
                "region": "福島県",
                "description": "爽やかな甘みと軽快な酸のバランスが絶妙。",
                "imagePath": "/images/sake-placeholder.jpg",
                "tags": [
                    {"label": "Balanced", "variant": "primary"},
                    {"label": "Year-round", "variant": "secondary"},
                ],
            },
            {
                "name": "紀土 純米吟醸",
                "brewery": "平和酒造",
                "region": "和歌山県",
                "description": "柔らかな甘みと、すっと消える爽やかな後味。",
                "imagePath": "/images/sake-placeholder.jpg",
                "tags": [
                    {"label": "Light", "variant": "primary"},
                    {"label": "Year-round", "variant": "secondary"},
                ],
            },
            {
                "name": "作 穂乃智",
                "brewery": "清水清三郎商店",
                "region": "三重県",
                "description": "優しい米の旨味と、穏やかな吟醸香の調和。",
                "imagePath": "/images/sake-placeholder.jpg",
                "tags": [
                    {"label": "Smooth", "variant": "primary"},
                    {"label": "Chilled", "variant": "secondary"},
                ],
            },
        ],
        "pairingSectionTitle": "風が通り抜ける食卓",
        "pairingSectionDescription": "SERSタイプは、素材の持ち味をそのまま活かす、自然体なペアリングが得意。肩の力を抜いて楽しめる組み合わせです。",
        "pairings": [
            {
                "emoji": "🐟",
                "foodName": "しめ鯖",
                "sakeName": "爽やかな純米吟醸",
                "temperature": "冷酒 10°C",
                "description": "酢の酸味と青魚の旨味に、軽快な酒がすっと馴染みます。",
            },
            {
                "emoji": "🥬",
                "foodName": "ほうれん草の胡麻和え",
                "sakeName": "穏やかな純米",
                "temperature": "常温",
                "description": "胡麻の風味と野菜の甘さに、酒の柔らかさが寄り添います。",
            },
            {
                "emoji": "🍢",
                "foodName": "だし巻き卵",
                "sakeName": "軽い本醸造",
                "temperature": "常温",
                "description": "出汁の旨味と卵の甘みが、酒の穏やかな味わいと自然に調和。",
            },
        ],
    },
    "SELB": {
        "sakes": [
            {
                "name": "十四代 本丸",
                "brewery": "高木酒造",
                "region": "山形県",
                "description": "本醸造ながら大吟醸を凌ぐフルーティーな香り。",
                "imagePath": "/images/sake-placeholder.jpg",
                "tags": [
                    {"label": "Premium", "variant": "primary"},
                    {"label": "Chilled", "variant": "secondary"},
                ],
            },
            {
                "name": "飛露喜 特別純米",
                "brewery": "廣木酒造",
                "region": "福島県",
                "description": "穏やかな甘みと、品のあるキレの良さ。",
                "imagePath": "/images/sake-placeholder.jpg",
                "tags": [
                    {"label": "Clean", "variant": "primary"},
                    {"label": "Year-round", "variant": "secondary"},
                ],
            },
            {
                "name": "磯自慢 特別本醸造",
                "brewery": "磯自慢酒造",
                "region": "静岡県",
                "description": "すっきりとした飲み口と、上品な旨味の余韻。",
                "imagePath": "/images/sake-placeholder.jpg",
                "tags": [
                    {"label": "Crisp", "variant": "primary"},
                    {"label": "Chilled", "variant": "secondary"},
                ],
            },
        ],
        "pairingSectionTitle": "気品ある享楽の時間",
        "pairingSectionDescription": "SELBタイプは、上質な素材をシンプルに楽しむペアリングが得意。気品と大胆さを兼ね備えた組み合わせをどうぞ。",
        "pairings": [
            {
                "emoji": "🐟",
                "foodName": "うに",
                "sakeName": "華やかな本醸造",
                "temperature": "冷酒 8°C",
                "description": "うにの濃厚な甘みと、酒のフルーティーな香りが贅沢に響き合います。",
            },
            {
                "emoji": "🥩",
                "foodName": "和牛タタキ",
                "sakeName": "キレのある純米",
                "temperature": "常温",
                "description": "肉の甘みを酒のすっきりした後味がスマートに流します。",
            },
            {
                "emoji": "🍡",
                "foodName": "あんこう肝ポン酢",
                "sakeName": "旨口の特別純米",
                "temperature": "冷酒 10°C",
                "description": "濃厚な肝の旨味を、ポン酢の酸と酒のキレが爽やかにまとめます。",
            },
        ],
    },
    "SELS": {
        "sakes": [
            {
                "name": "久保田 萬寿",
                "brewery": "朝日酒造",
                "region": "新潟県",
                "description": "柔らかく深い味わいと、上品な香りの調和。",
                "imagePath": "/images/sake-placeholder.jpg",
                "tags": [
                    {"label": "Rich", "variant": "primary"},
                    {"label": "Chilled", "variant": "secondary"},
                ],
            },
            {
                "name": "越乃寒梅 白ラベル",
                "brewery": "石本酒造",
                "region": "新潟県",
                "description": "端正ですっきり。新潟淡麗の教科書的存在。",
                "imagePath": "/images/sake-placeholder.jpg",
                "tags": [
                    {"label": "Classic", "variant": "primary"},
                    {"label": "Year-round", "variant": "secondary"},
                ],
            },
            {
                "name": "真澄 純米吟醸",
                "brewery": "宮坂醸造",
                "region": "長野県",
                "description": "7号酵母発祥の蔵。穏やかで調和のとれた味わい。",
                "imagePath": "/images/sake-placeholder.jpg",
                "tags": [
                    {"label": "Harmonious", "variant": "primary"},
                    {"label": "Year-round", "variant": "secondary"},
                ],
            },
        ],
        "pairingSectionTitle": "優しい調和の食卓",
        "pairingSectionDescription": "SELSタイプは、穏やかな味わい同士が静かに寄り添うペアリングが得意。日常の食事を上品に彩ります。",
        "pairings": [
            {
                "emoji": "🍲",
                "foodName": "おでん",
                "sakeName": "穏やかな純米大吟醸",
                "temperature": "常温",
                "description": "出汁の旨味と酒のまろやかさが、冬の夜を温かく包みます。",
            },
            {
                "emoji": "🐟",
                "foodName": "かつおの藁焼き",
                "sakeName": "キレのある純米",
                "temperature": "冷酒 10°C",
                "description": "藁の香ばしさとかつおの力強さを、酒のすっきりさが引き締めます。",
            },
            {
                "emoji": "🥬",
                "foodName": "筍の木の芽和え",
                "sakeName": "春の純米吟醸",
                "temperature": "冷酒 12°C",
                "description": "春の香りと筍の食感に、爽やかな酒が季節感を添えます。",
            },
        ],
    },
    "DHRB": {
        "sakes": [
            {
                "name": "田酒 特別純米",
                "brewery": "西田酒造店",
                "region": "青森県",
                "description": "米の旨味を最大限に引き出した骨太な味わい。",
                "imagePath": "/images/sake-placeholder.jpg",
                "tags": [
                    {"label": "Bold", "variant": "primary"},
                    {"label": "Warm", "variant": "secondary"},
                ],
            },
            {
                "name": "菊姫 山廃純米",
                "brewery": "菊姫合資会社",
                "region": "石川県",
                "description": "山廃仕込みの奥深いコクと、骨格のある味わい。",
                "imagePath": "/images/sake-placeholder.jpg",
                "tags": [
                    {"label": "Complex", "variant": "primary"},
                    {"label": "Warm", "variant": "secondary"},
                ],
            },
            {
                "name": "大七 純米生もと",
                "brewery": "大七酒造",
                "region": "福島県",
                "description": "生もと造りの力強い酸と、深い旨味の重層感。",
                "imagePath": "/images/sake-placeholder.jpg",
                "tags": [
                    {"label": "Traditional", "variant": "primary"},
                    {"label": "Hot", "variant": "secondary"},
                ],
            },
        ],
        "pairingSectionTitle": "深淵の味わいの探求",
        "pairingSectionDescription": "DHRBタイプは、力強い味わい同士がぶつかり合い高め合うペアリングが得意。骨太な料理との組み合わせをどうぞ。",
        "pairings": [
            {
                "emoji": "🫕",
                "foodName": "もつ鍋",
                "sakeName": "山廃仕込みの純米",
                "temperature": "ぬる燗 40°C",
                "description": "もつの濃厚な旨味を、山廃の力強い酸とコクが受け止めます。",
            },
            {
                "emoji": "🥩",
                "foodName": "牛すじ煮込み",
                "sakeName": "骨太な特別純米",
                "temperature": "熱燗 50°C",
                "description": "じっくり煮込まれた旨味に、熱燗の深いコクが寄り添います。",
            },
            {
                "emoji": "🐟",
                "foodName": "ぶりのかま焼き",
                "sakeName": "生もとの純米",
                "temperature": "ぬる燗 40°C",
                "description": "脂の乗ったぶりと、生もとの力強い酸が絶妙な対比を生みます。",
            },
        ],
    },
    "DHRS": {
        "sakes": [
            {
                "name": "黒龍 大吟醸",
                "brewery": "黒龍酒造",
                "region": "福井県",
                "description": "控えめながら品のある吟醸香と、なめらかな口当たり。",
                "imagePath": "/images/sake-placeholder.jpg",
                "tags": [
                    {"label": "Refined", "variant": "primary"},
                    {"label": "Chilled", "variant": "secondary"},
                ],
            },
            {
                "name": "〆張鶴 純",
                "brewery": "宮尾酒造",
                "region": "新潟県",
                "description": "端正で品のある味わい。辛口ながら柔らかさも持つ。",
                "imagePath": "/images/sake-placeholder.jpg",
                "tags": [
                    {"label": "Polished", "variant": "primary"},
                    {"label": "Year-round", "variant": "secondary"},
                ],
            },
            {
                "name": "梵 GOLD 純米大吟醸",
                "brewery": "加藤吉平商店",
                "region": "福井県",
                "description": "熟成による深みと、洗練された香りの調和。",
                "imagePath": "/images/sake-placeholder.jpg",
                "tags": [
                    {"label": "Aged", "variant": "primary"},
                    {"label": "Room Temp", "variant": "secondary"},
                ],
            },
        ],
        "pairingSectionTitle": "洗練された求道の一杯",
        "pairingSectionDescription": "DHRSタイプは、繊細さと深みを兼ね備えたペアリングが得意。丁寧な料理との静かな対話を楽しんでください。",
        "pairings": [
            {
                "emoji": "🐟",
                "foodName": "鰤しゃぶ",
                "sakeName": "端正な大吟醸",
                "temperature": "冷酒 10°C",
                "description": "さっと火を通したぶりの甘みに、酒の上品な香りが華を添えます。",
            },
            {
                "emoji": "🍲",
                "foodName": "茶碗蒸し",
                "sakeName": "なめらかな純米吟醸",
                "temperature": "常温",
                "description": "出汁の旨味と卵の優しさに、酒の柔らかさが心安らぐハーモニー。",
            },
            {
                "emoji": "🥬",
                "foodName": "白子ポン酢",
                "sakeName": "キレのある辛口",
                "temperature": "冷酒 8°C",
                "description": "白子の濃厚さをポン酢と酒のキレがすっきりとまとめます。",
            },
        ],
    },
    "DHLB": {
        "sakes": [
            {
                "name": "八海山 特別本醸造",
                "brewery": "八海醸造",
                "region": "新潟県",
                "description": "淡麗辛口の代名詞。キレ味抜群の食中酒。",
                "imagePath": "/images/sake-placeholder.jpg",
                "tags": [
                    {"label": "Dry", "variant": "primary"},
                    {"label": "Room Temp", "variant": "secondary"},
                ],
            },
            {
                "name": "立山 特別本醸造",
                "brewery": "立山酒造",
                "region": "富山県",
                "description": "キレ良くすっきり。毎日の食卓に寄り添う辛口。",
                "imagePath": "/images/sake-placeholder.jpg",
                "tags": [
                    {"label": "Clean", "variant": "primary"},
                    {"label": "Year-round", "variant": "secondary"},
                ],
            },
            {
                "name": "一ノ蔵 無鑑査",
                "brewery": "一ノ蔵",
                "region": "宮城県",
                "description": "すっきりとした飲み口と、食事を選ばない万能さ。",
                "imagePath": "/images/sake-placeholder.jpg",
                "tags": [
                    {"label": "Versatile", "variant": "primary"},
                    {"label": "Year-round", "variant": "secondary"},
                ],
            },
        ],
        "pairingSectionTitle": "揺るぎない定番の力",
        "pairingSectionDescription": "DHLBタイプは、王道の組み合わせを極めるペアリングが得意。定番の中にこそある深い満足を味わってください。",
        "pairings": [
            {
                "emoji": "🐟",
                "foodName": "塩焼き（鮭・鯖）",
                "sakeName": "キレのある辛口本醸造",
                "temperature": "常温",
                "description": "魚の脂をすっきり流す、毎日の晩酌の黄金ペアリング。",
            },
            {
                "emoji": "🍢",
                "foodName": "焼きそば",
                "sakeName": "すっきり系の辛口",
                "temperature": "冷酒 10°C",
                "description": "ソースの濃い味をキレの良い辛口がさっぱりリセット。",
            },
            {
                "emoji": "🥬",
                "foodName": "きゅうりの浅漬け",
                "sakeName": "淡麗な本醸造",
                "temperature": "冷酒 8°C",
                "description": "シンプルな美味しさ。野菜の爽やかさと辛口の心地よいキレ。",
            },
        ],
    },
    "DHLS": {
        "sakes": [
            {
                "name": "久保田 千寿",
                "brewery": "朝日酒造",
                "region": "新潟県",
                "description": "料理を引き立てる、すっきりとした吟醸酒。",
                "imagePath": "/images/sake-placeholder.jpg",
                "tags": [
                    {"label": "Light", "variant": "primary"},
                    {"label": "Year-round", "variant": "secondary"},
                ],
            },
            {
                "name": "浦霞 禅",
                "brewery": "佐浦",
                "region": "宮城県",
                "description": "穏やかで落ち着いた味わい。名前の通り禅の心。",
                "imagePath": "/images/sake-placeholder.jpg",
                "tags": [
                    {"label": "Calm", "variant": "primary"},
                    {"label": "Year-round", "variant": "secondary"},
                ],
            },
            {
                "name": "月山 純米吟醸",
                "brewery": "吉田酒造",
                "region": "島根県",
                "description": "柔らかな口当たりと、控えめな吟醸香。",
                "imagePath": "/images/sake-placeholder.jpg",
                "tags": [
                    {"label": "Quiet", "variant": "primary"},
                    {"label": "Room Temp", "variant": "secondary"},
                ],
            },
        ],
        "pairingSectionTitle": "静かな哲学の食卓",
        "pairingSectionDescription": "DHLSタイプは、控えめでありながら奥深い味わいの中に真実を見出すペアリングが得意。静かに味わう幸せを。",
        "pairings": [
            {
                "emoji": "🍲",
                "foodName": "肉じゃが",
                "sakeName": "穏やかな吟醸",
                "temperature": "常温",
                "description": "家庭の味に寄り添う、温かく優しいペアリング。",
            },
            {
                "emoji": "🐟",
                "foodName": "焼き魚定食",
                "sakeName": "すっきりした純米",
                "temperature": "常温",
                "description": "日常の食事を少しだけ特別にする、控えめな贅沢。",
            },
            {
                "emoji": "🥬",
                "foodName": "冷や奴",
                "sakeName": "軽い本醸造",
                "temperature": "冷酒 10°C",
                "description": "豆腐の繊細な甘みと、酒のすっきりした味わいが静かに調和。",
            },
        ],
    },
    "DERB": {
        "sakes": [
            {
                "name": "新政 Colors 瑠璃",
                "brewery": "新政酒造",
                "region": "秋田県",
                "description": "革新的な酸味とドライな飲み口。ワイン通も唸る。",
                "imagePath": "/images/sake-placeholder.jpg",
                "tags": [
                    {"label": "Innovative", "variant": "primary"},
                    {"label": "Chilled", "variant": "secondary"},
                ],
            },
            {
                "name": "仙禽 モダン仙禽",
                "brewery": "せんきん",
                "region": "栃木県",
                "description": "甘酸っぱさとドライさが共存する不思議な魅力。",
                "imagePath": "/images/sake-placeholder.jpg",
                "tags": [
                    {"label": "Modern", "variant": "primary"},
                    {"label": "Chilled", "variant": "secondary"},
                ],
            },
            {
                "name": "天吹 純米大吟醸",
                "brewery": "天吹酒造",
                "region": "佐賀県",
                "description": "花酵母が生む独特の香りと、キレのある味わい。",
                "imagePath": "/images/sake-placeholder.jpg",
                "tags": [
                    {"label": "Floral", "variant": "primary"},
                    {"label": "Year-round", "variant": "secondary"},
                ],
            },
        ],
        "pairingSectionTitle": "知的好奇心の饗宴",
        "pairingSectionDescription": "DERBタイプは、意外性のある大胆な組み合わせを楽しむのが得意。新しい味の発見を恐れずに。",
        "pairings": [
            {
                "emoji": "🧀",
                "foodName": "シェーヴルチーズ",
                "sakeName": "酸の効いた純米",
                "temperature": "冷酒 8°C",
                "description": "ヤギのチーズの酸味と酒の乳酸が、フランス的なマリアージュ。",
            },
            {
                "emoji": "🐟",
                "foodName": "カルパッチョ",
                "sakeName": "ドライな純米吟醸",
                "temperature": "冷酒 10°C",
                "description": "オリーブオイルと柑橘の白身魚に、酒のシャープさが映えます。",
            },
            {
                "emoji": "🍗",
                "foodName": "スパイスチキン",
                "sakeName": "個性的な純米",
                "temperature": "常温",
                "description": "スパイスの複雑さを酒の酸が整理し、新しい味の地平を開きます。",
            },
        ],
    },
    "DERS": {
        "sakes": [
            {
                "name": "醸し人九平次 別誂",
                "brewery": "萬乗醸造",
                "region": "愛知県",
                "description": "ワインのようなエレガンスと、深い余韻。",
                "imagePath": "/images/sake-placeholder.jpg",
                "tags": [
                    {"label": "Elegant", "variant": "primary"},
                    {"label": "Room Temp", "variant": "secondary"},
                ],
            },
            {
                "name": "鳳凰美田 髭判",
                "brewery": "小林酒造",
                "region": "栃木県",
                "description": "穏やかな酸と、すっと消える爽やかな余韻。",
                "imagePath": "/images/sake-placeholder.jpg",
                "tags": [
                    {"label": "Smooth", "variant": "primary"},
                    {"label": "Chilled", "variant": "secondary"},
                ],
            },
            {
                "name": "楯野川 純米大吟醸",
                "brewery": "楯の川酒造",
                "region": "山形県",
                "description": "全量純米大吟醸蔵の、繊細で流れるような味わい。",
                "imagePath": "/images/sake-placeholder.jpg",
                "tags": [
                    {"label": "Flowing", "variant": "primary"},
                    {"label": "Chilled", "variant": "secondary"},
                ],
            },
        ],
        "pairingSectionTitle": "流れるように味わう",
        "pairingSectionDescription": "DERSタイプは、繊細でエレガントな味わいの流れを楽しむペアリングが得意。余韻の美しさを大切に。",
        "pairings": [
            {
                "emoji": "🐟",
                "foodName": "平目の刺身",
                "sakeName": "エレガントな純米大吟醸",
                "temperature": "冷酒 10°C",
                "description": "平目の上品な甘みに、酒の繊細な香りが静かに重なります。",
            },
            {
                "emoji": "🥗",
                "foodName": "白桃とモッツァレラ",
                "sakeName": "フルーティーな吟醸",
                "temperature": "冷酒 8°C",
                "description": "果実の甘みとチーズの優しさを、酒がエレガントに繋ぎます。",
            },
            {
                "emoji": "🍲",
                "foodName": "鯛めし",
                "sakeName": "上品な純米吟醸",
                "temperature": "常温",
                "description": "鯛と出汁の旨味が凝縮した一品に、酒の余韻が溶け込みます。",
            },
        ],
    },
    "DELB": {
        "sakes": [
            {
                "name": "土佐しらぎく 特別純米",
                "brewery": "仙頭酒造場",
                "region": "高知県",
                "description": "土佐流の辛口。キレがよく、料理を立てる食中酒。",
                "imagePath": "/images/sake-placeholder.jpg",
                "tags": [
                    {"label": "Sharp", "variant": "primary"},
                    {"label": "Room Temp", "variant": "secondary"},
                ],
            },
            {
                "name": "南 特別純米",
                "brewery": "南酒造場",
                "region": "高知県",
                "description": "すっきりとした中にも米の旨味が光る、本格派の辛口。",
                "imagePath": "/images/sake-placeholder.jpg",
                "tags": [
                    {"label": "Dry", "variant": "primary"},
                    {"label": "Year-round", "variant": "secondary"},
                ],
            },
            {
                "name": "秋鹿 純米",
                "brewery": "秋鹿酒造",
                "region": "大阪府",
                "description": "自家栽培米で醸す、骨格のある辛口純米。",
                "imagePath": "/images/sake-placeholder.jpg",
                "tags": [
                    {"label": "Earthy", "variant": "primary"},
                    {"label": "Warm", "variant": "secondary"},
                ],
            },
        ],
        "pairingSectionTitle": "大地に根ざした味わい",
        "pairingSectionDescription": "DELBタイプは、素材の力強さを引き出す実直なペアリングが得意。飾らない美味しさの中に本質を見出します。",
        "pairings": [
            {
                "emoji": "🐟",
                "foodName": "かつおの塩たたき",
                "sakeName": "辛口の特別純米",
                "temperature": "常温",
                "description": "かつおの力強い旨味に、辛口の酒のキレが痛快にマッチ。",
            },
            {
                "emoji": "🍢",
                "foodName": "焼き鳥（塩）",
                "sakeName": "キレのある純米",
                "temperature": "常温",
                "description": "塩の旨味と鶏の脂を、辛口の酒がすっきりと流します。",
            },
            {
                "emoji": "🥬",
                "foodName": "ぬか漬け",
                "sakeName": "骨格のある純米",
                "temperature": "ぬる燗 40°C",
                "description": "発酵食品同士の共鳴。ぬかの旨味と酒のコクが深く調和します。",
            },
        ],
    },
    "DELS": {
        "sakes": [
            {
                "name": "八海山 純米大吟醸",
                "brewery": "八海醸造",
                "region": "新潟県",
                "description": "淡麗でありながら、奥行きのある繊細な味わい。",
                "imagePath": "/images/sake-placeholder.jpg",
                "tags": [
                    {"label": "Delicate", "variant": "primary"},
                    {"label": "Chilled", "variant": "secondary"},
                ],
            },
            {
                "name": "水芭蕉 純米吟醸",
                "brewery": "永井酒造",
                "region": "群馬県",
                "description": "水のように澄んだ味わいと、さらりとした飲み口。",
                "imagePath": "/images/sake-placeholder.jpg",
                "tags": [
                    {"label": "Crystal", "variant": "primary"},
                    {"label": "Year-round", "variant": "secondary"},
                ],
            },
            {
                "name": "天狗舞 山廃純米",
                "brewery": "車多酒造",
                "region": "石川県",
                "description": "山廃ながら軽快。複雑さと飲みやすさの両立。",
                "imagePath": "/images/sake-placeholder.jpg",
                "tags": [
                    {"label": "Nuanced", "variant": "primary"},
                    {"label": "Room Temp", "variant": "secondary"},
                ],
            },
        ],
        "pairingSectionTitle": "透明な旅路の一皿",
        "pairingSectionDescription": "DELSタイプは、透明感のある味わいの中に旅情を見出すペアリングが得意。静かに広がる余韻を楽しんで。",
        "pairings": [
            {
                "emoji": "🐟",
                "foodName": "甘海老の刺身",
                "sakeName": "繊細な純米大吟醸",
                "temperature": "冷酒 8°C",
                "description": "甘海老のとろける甘みに、酒の透明感が寄り添います。",
            },
            {
                "emoji": "🍲",
                "foodName": "鶏つくねの水炊き",
                "sakeName": "穏やかな純米吟醸",
                "temperature": "常温",
                "description": "澄んだスープの旨味と、酒の柔らかさが優しく調和します。",
            },
            {
                "emoji": "🥬",
                "foodName": "山菜の天ぷら",
                "sakeName": "軽快な山廃純米",
                "temperature": "常温",
                "description": "山菜のほろ苦さとサクッとした衣に、酒のキレが爽やかなアクセント。",
            },
        ],
    },
}
